C     RESERVOIR SAMPLING -- ALGORITHM R
C     ( A. G. WATERMAN, UNPUBLISHED; S. KNUTH, TAOCP VOL. 2,
C       SEMINUMERICAL ALGORITHMS, SEC. 3.4.2 )
C
C     TEN LINES ARE DRAWN BY LOT FROM A STREAM OF UNKNOWN LENGTH,
C     READ ONCE AND NEVER AGAIN.  EACH NEW LINE MAY, WITH DWINDLING
C     PROBABILITY, STRIKE ONE OF THE CHOSEN FROM THE RESERVOIR AND
C     TAKE ITS PLACE.  AT THE END OF THE STREAM EACH LINE, LIVING
C     OR DROWNED, HAS HAD EXACTLY THE SAME CHANCE:  10/N.
C
C       gfortran -std=legacy -o reservoir reservoir.f
C       ./reservoir < king_james_bible.txt
C
      PROGRAM RESVR
      CHARACTER*80 LINE
      CHARACTER*80 KEEP(10)
      INTEGER N, I, J
      REAL R
C
      CALL SRAND(TIME())
      N = 0
C
   10 READ (*, '(A)', END = 30) LINE
      IF (LINE .EQ. ' ') GO TO 10
      N = N + 1
      IF (N .GT. 10) GO TO 20
      KEEP(N) = LINE
      GO TO 10
C
C     THE LOT IS CAST INTO THE LAP
   20 R = RAND(0)
      J = INT(R * REAL(N)) + 1
      IF (J .LE. 10) KEEP(J) = LINE
      GO TO 10
C
   30 IF (N .LT. 10) STOP 'THE STREAM RAN DRY TOO SOON'
      WRITE (*, 40) N
   40 FORMAT ('TEN LINES DRAWN BY LOT FROM A STREAM OF ', I6, ':' /)
      DO 50 I = 1, 10
      WRITE (*, '(A)') KEEP(I)
   50 CONTINUE
      END
